.TH MYSTRLEN 3 "2024-01-01" "libmyutils" "User Commands"
.SH NAME
mystrlen \- get the length of a string
.SH SYNOPSIS
.B int mystrlen(const char* s);
.SH DESCRIPTION
.B mystrlen
calculates the length of the string pointed to by
.IR s ,
excluding the terminating null byte ('\\0').
.PP
Returns the number of characters in the string.
.SH AUTHOR
Abdullah (abdullah2k05@users.noreply.github.com)
