.TH MYSTRCPY 3 "2024-01-01" "libmyutils" "User Commands"
.SH NAME
mystrcpy \- copy a string
.SH SYNOPSIS
.B int mystrcpy(char* dest, const char* src);
.SH DESCRIPTION
.B mystrcpy
copies the string pointed to by
.I src
(including the terminating null byte) to the buffer pointed to by
.IR dest .
.PP
Returns the number of characters copied.
.SH AUTHOR
Abdullah (abdullah2k05@users.noreply.github.com)
