.TH MYSTRCAT 3 "2024-01-01" "libmyutils" "User Commands"
.SH NAME
mystrcat \- concatenate two strings
.SH SYNOPSIS
.B int mystrcat(char* dest, const char* src);
.SH DESCRIPTION
.B mystrcat
appends the string pointed to by
.I src
to the end of the string pointed to by
.IR dest .
.PP
Returns the total length of the concatenated string.
.SH AUTHOR
Abdullah (abdullah2k05@users.noreply.github.com)
